/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedMyListRouteImport } from './routes/_authenticated/my-list'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AnimeIndexRouteImport } from './routes/anime.index'
import { Route as AnimeIdRouteImport } from './routes/anime.$id'
import { Route as MangaIndexRouteImport } from './routes/manga.index'
import { Route as MangaIdRouteImport } from './routes/manga.$id'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as NewsSlugRouteImport } from './routes/news.$slug'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as ApiPublicWebhooksKobaraRouteImport } from './routes/api/public/webhooks/kobara'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyListRoute = AuthenticatedMyListRouteImport.update({
  id: '/my-list',
  path: '/my-list',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AnimeIndexRoute = AnimeIndexRouteImport.update({
  id: '/anime/',
  path: '/anime/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIdRoute = AnimeIdRouteImport.update({
  id: '/anime/$id',
  path: '/anime/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaIndexRoute = MangaIndexRouteImport.update({
  id: '/manga/',
  path: '/manga/',
  getParentRoute: () => rootRouteImport,
} as any)
const MangaIdRoute = MangaIdRouteImport.update({
  id: '/manga/$id',
  path: '/manga/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksKobaraRoute = ApiPublicWebhooksKobaraRouteImport.update({
  id: '/api/public/webhooks/kobara',
  path: '/api/public/webhooks/kobara',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/my-list': typeof AuthenticatedMyListRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/anime/$id': typeof AnimeIdRoute
  '/manga/$id': typeof MangaIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/anime/': typeof AnimeIndexRoute
  '/manga/': typeof MangaIndexRoute
  '/news/': typeof NewsIndexRoute
  '/api/public/webhooks/kobara': typeof ApiPublicWebhooksKobaraRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/my-list': typeof AuthenticatedMyListRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/anime/$id': typeof AnimeIdRoute
  '/manga/$id': typeof MangaIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/anime': typeof AnimeIndexRoute
  '/manga': typeof MangaIndexRoute
  '/news': typeof NewsIndexRoute
  '/api/public/webhooks/kobara': typeof ApiPublicWebhooksKobaraRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/calendar': typeof CalendarRoute
  '/community': typeof CommunityRoute
  '/explore': typeof ExploreRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/my-list': typeof AuthenticatedMyListRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/anime/$id': typeof AnimeIdRoute
  '/manga/$id': typeof MangaIdRoute
  '/news/$slug': typeof NewsSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/anime/': typeof AnimeIndexRoute
  '/manga/': typeof MangaIndexRoute
  '/news/': typeof NewsIndexRoute
  '/api/public/webhooks/kobara': typeof ApiPublicWebhooksKobaraRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/community'
    | '/explore'
    | '/login'
    | '/search'
    | '/admin'
    | '/favorites'
    | '/my-list'
    | '/notifications'
    | '/settings'
    | '/anime/$id'
    | '/manga/$id'
    | '/news/$slug'
    | '/profile/$username'
    | '/anime/'
    | '/manga/'
    | '/news/'
    | '/api/public/webhooks/kobara'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/community'
    | '/explore'
    | '/login'
    | '/search'
    | '/admin'
    | '/favorites'
    | '/my-list'
    | '/notifications'
    | '/settings'
    | '/anime/$id'
    | '/manga/$id'
    | '/news/$slug'
    | '/profile/$username'
    | '/anime'
    | '/manga'
    | '/news'
    | '/api/public/webhooks/kobara'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/calendar'
    | '/community'
    | '/explore'
    | '/login'
    | '/search'
    | '/_authenticated/admin'
    | '/_authenticated/favorites'
    | '/_authenticated/my-list'
    | '/_authenticated/notifications'
    | '/_authenticated/settings'
    | '/anime/$id'
    | '/manga/$id'
    | '/news/$slug'
    | '/profile/$username'
    | '/anime/'
    | '/manga/'
    | '/news/'
    | '/api/public/webhooks/kobara'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CalendarRoute: typeof CalendarRoute
  CommunityRoute: typeof CommunityRoute
  ExploreRoute: typeof ExploreRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  AnimeIdRoute: typeof AnimeIdRoute
  MangaIdRoute: typeof MangaIdRoute
  NewsSlugRoute: typeof NewsSlugRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  AnimeIndexRoute: typeof AnimeIndexRoute
  MangaIndexRoute: typeof MangaIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  ApiPublicWebhooksKobaraRoute: typeof ApiPublicWebhooksKobaraRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-list': {
      id: '/_authenticated/my-list'
      path: '/my-list'
      fullPath: '/my-list'
      preLoaderRoute: typeof AuthenticatedMyListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/anime/': {
      id: '/anime/'
      path: '/anime'
      fullPath: '/anime/'
      preLoaderRoute: typeof AnimeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$id': {
      id: '/anime/$id'
      path: '/anime/$id'
      fullPath: '/anime/$id'
      preLoaderRoute: typeof AnimeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/': {
      id: '/manga/'
      path: '/manga'
      fullPath: '/manga/'
      preLoaderRoute: typeof MangaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manga/$id': {
      id: '/manga/$id'
      path: '/manga/$id'
      fullPath: '/manga/$id'
      preLoaderRoute: typeof MangaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$slug': {
      id: '/news/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/kobara': {
      id: '/api/public/webhooks/kobara'
      path: '/api/public/webhooks/kobara'
      fullPath: '/api/public/webhooks/kobara'
      preLoaderRoute: typeof ApiPublicWebhooksKobaraRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedMyListRoute: typeof AuthenticatedMyListRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedMyListRoute: AuthenticatedMyListRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CalendarRoute: CalendarRoute,
  CommunityRoute: CommunityRoute,
  ExploreRoute: ExploreRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  AnimeIdRoute: AnimeIdRoute,
  MangaIdRoute: MangaIdRoute,
  NewsSlugRoute: NewsSlugRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  AnimeIndexRoute: AnimeIndexRoute,
  MangaIndexRoute: MangaIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  ApiPublicWebhooksKobaraRoute: ApiPublicWebhooksKobaraRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
